# These are from default_config, with the ones that I don't need
# commented out. It would be nice if the default_config: could have
# an exclude list, to stay in sync with the distributed defaults,
# but currently this is not possible.(I have seen talk about it as
# an implementation idea though.
#automation:
#cloud:
config:
#frontend:
#history:
logbook:
#map:
#mobile_app:
person:
#script:
#ssdp:
#sun:
system_health:
updater:
#zeroconf:

# The home-assistant server lives behind a proxy.
http:
  base_url: !secret http-proxy-base-url
  use_x_forwarded_for: true
  trusted_proxies: !secret http-proxy-ip-address

recorder:
  db_url: postgresql://@/homeassistant
  purge_keep_days: 1
  purge_interval: 1
#  include:
#    domains:
#      - switch
#      - sensor
#      - binary_sensor
#  exclude:
#    event_types:
#      - call_service
#      - state_changed
#      - timer.cancelled
#      - automation_trigered
#    domains:
#      - light
#    entities:
#      - switch.ambilite
#      - sensor.date_time
#      - sensor.time
#      - sun.sun
#      - sensor.gas_consumption
#      - sensor.long_power_failure_count
#      - sensor.power_consumption_low
#      - sensor.power_consumption_normal
#      - sensor.power_consumption_phase_l1
#      - sensor.power_consumption_phase_l2
#      - sensor.power_consumption_phase_l3
#      - sensor.power_production
#      - sensor.power_production_low
#      - sensor.power_production_normal
#      - sensor.power_production_phase_l1
#      - sensor.power_production_phase_l2
#      - sensor.power_production_phase_l3
#      - sensor.power_tariff
#      - sensor.voltage_phase_l1
#      - sensor.voltage_phase_l2
#      - sensor.voltage_phase_l3
#      - sensor.voltage_sags_phase_l1
#      - sensor.voltage_sags_phase_l2
#      - sensor.voltage_sags_phase_l3
#      - sensor.voltage_swells_phase_l1
#      - switch.stekker_tvkast_rechts
#      - switch.stekker_tvkast_rechts_2
#      - switch.stekker_tvkast_links
#      - switch.stekker_tvkast_links_2
#      - sensor.dar_voorkant_gft
#      - sensor.dar_voorkant_papier
#      - sensor.dar_voorkant_restafval
#      - sensor.dar_voorkant_vandaag
#      - sensor.dar_voorkant_morgen
#      - sensor.dar_zijkant_papier
#      - sensor.dar_zijkant_vandaag
#      - sensor.dar_zijkant_morgen

#logger:
#  default: debug

# Expose a Prometheus metrics endpoint.
prometheus:
  namespace: hass
  filter:
    include_domains:
      - binary_sensor
      - sensor
    exclude_entities:
      - sensor.dar_voorkant_gft
      - sensor.dar_voorkant_papier
      - sensor.dar_voorkant_restafval
      - sensor.dar_voorkant_vandaag
      - sensor.dar_voorkant_morgen
      - sensor.dar_zijkant_papier
      - sensor.dar_zijkant_vandaag
      - sensor.dar_zijkant_morgen
      - sensor.power_consumption_phase_l1
      - sensor.power_consumption_phase_l2
      - sensor.power_consumption_phase_l3
      - sensor.power_production
      - sensor.power_production_low
      - sensor.power_production_normal
      - sensor.power_production_phase_l1
      - sensor.power_production_phase_l2
      - sensor.power_production_phase_l3
      - sensor.power_tariff
      - sensor.voltage_phase_l1
      - sensor.voltage_phase_l2
      - sensor.voltage_phase_l3
      - sensor.voltage_sags_phase_l1
      - sensor.voltage_sags_phase_l2
      - sensor.voltage_sags_phase_l3
      - sensor.voltage_swells_phase_l1
      - sensor.br_pressure
      - sensor.br_humidity
      - sensor.br_symbol
      - sensor.br_wind_speed
      - sensor.last_update_trigger
      - sensor.bssid
      - sensor.connection_type
      - sensor.sim_1
      - sensor.ssid
      - sensor.geocoded_location
      - sensor.periode_van_de_dag
      - binary_sensor.woonkamer_lights_active
      - binary_sensor.woonkamer_power_active
      - binary_sensor.keuken_lights_active

frontend:
  themes: !include themes.yaml

# These must be included like stated here, in order to make
# it possible to edit these customization through the GUI.
script: !include_dir_merge_named scripts/
scene: !include scenes.yaml
homeassistant:
  customize: !include customize.yaml

# Automation old is for manual automation files. The 
# auomations.yaml is used for automations that are
# edited through the admin GUI.
automation: !include automations.yaml
automation old: !include_dir_merge_list automation

sensor: !include_dir_list sensors

binary_sensor: !include_dir_list binary_sensors

timer: !include_dir_merge_named timers

light: !include_dir_list lights

switch: !include_dir_list switches

fritzbox:
  devices:
    - host: !secret fritzbox-host
      username: !secret fritzbox-home-assistant-username
      password: !secret fritzbox-home-assistant-password

media_player:
  - platform: braviatv
    host: !secret braviatv-ip-address

# Experiment to link the iTV set top box, but can't get it
# to work at this moment (or possibly ever).
#device_tracker:
#  - platform: bluetooth_le_tracker
#    track_new_devices: true

proximity:
  maurice:
    ignored_zones:
      - home
    devices:
      - device_tracker.owntracks_maurice
    tolerance: 50
    unit_of_measurement: km

shopping_list:

mqtt:
  broker: !secret mosquitto-host
  port: !secret mosquitto-port
  username: !secret mosquitto-username
  password: !secret mosquitto-password
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: 'homeassistant/status'
    payload: 'online'
  will_message:
    topic: 'homeassistant/status'
    payload: 'offline'

# Running into av dependency issues:
# https://github.com/home-assistant/home-assistant/issues/26251
# https://github.com/home-assistant/home-assistant/issues/26711
# Fix:
# $ sudo apt-get install -y python-dev pkg-config libavformat-dev \
#   libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev \
#   libavresample-dev libavfilter-dev
# $ hacheckconf
#camera:
#  - platform: mqtt
#    unique_id: ambilite
#    name: ambilite
#    topic: homeassistant/switch/ambilite/television
#  - platform: mqtt
#    unique_id: settopbox
#    name: settopbox
#    topic: homeassistant/switch/ambilite/settopbox
